version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.be
    ports:
      - "3000:3000"
    container_name: inventory-app-backend
    

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.fe
    ports:
      - "4173:4173"
    container_name: inventory-app-frontend
    depends_on:
      - backend